@startuml classDiagram

class Cliente {
    -String nome
    -long rg
    -long cpf
    -String endereco
    -String profissao
    -List<String> empregadores
    -List<Double> rendimentos
    -List<Pedido> pedidos
    +Cliente(String nome, long rg, long cpf, String endereco, String profissao, List<String> empregadores, List<Double> rendimentos)
    +void adicionarPedido(Pedido pedido)
    +void modificarPedido(Pedido pedido)
    +void consultarPedido(Pedido pedido)
    +void cancelarPedido(Pedido pedido)
}

class Empresa {
    -String nome
    -List<Pedido> pedidos
    +Empresa(String nome)
    +void modificarPedido(Pedido pedido)
    +void aprovarPedido(Pedido pedido)
    +Contrato criarContrato(Pedido pedido)
}

class Banco {
    +ContratoCredito aprovarContratoCredito(Pedido pedido)
}

class Pedido {
    -Cliente cliente
    -Automovel automovel
    -Duracao duracao
    -Boolean aprovado
    -Date dataAprovacao
    +Pedido(Cliente cliente, Automovel automovel, Duracao duracao)
}

class Automovel {
    -String matricula
    -int ano
    -String marca
    -String modelo
    -String placa
    +Automovel(String matricula, int ano, String marca, String modelo, String placa)
}

class Contrato {
    -Pedido pedido
    -Empresa empresa
    +Contrato(Pedido pedido, Empresa empresa)
}

class ContratoCredito {
    +ContratoCredito(Pedido pedido, Banco banco) 
}

class Locacao {
    -Pedido pedido 
    -Empresa avaliador
    -Banco avaliadorCredito
    -Date dataInicio
    +Locacao(Pedido pedido, Empresa avaliador)
}

enum Duracao {
    12_MESES
    24_MESES
    36_MESES
    48_MESES
}

Cliente "1" --o "1..*" Pedido
Pedido "1" --o "0..1" Locacao
Empresa "1" *-- "0..*" Contrato
Empresa "1" o-- "0..*" Locacao
Pedido "0..*" o-- "1" Automovel
Empresa <|-- Banco
Contrato <|-- ContratoCredito

@enduml