@startuml
interface "REST" as R1

[Client] <.. R1

node "SpringBoot" as C1 {
[Veiculo]
[Cliente]
[Locacao]
[Empresa]
[Contrato]
[ContratoCredito]
}

C1 -up- R1

interface "TCP/IP" as T1

database "PostgreSQL" as PG {
}

T1 - PG
C1 -right-> T1

@enduml