@startuml useCaseDiagram

:Usuário: as U
:Banco: as B
:Empresa: as E

B --|> E

(Introduzir pedido de aluguel) as IntroPedido
(Cancelar pedido de aluguel) as CancelarPedido
(Consultar pedido de aluguel) as ConsultarPedido
(Modificar pedido de aluguel) as ModificarPedido

(Analisar pedido de aluguel) as AnalisarPedido

(Considerar execução do contrato) as ConsultarViabilidade

(Conceder contrato de crédito) as ConcederContrato

U -- IntroPedido
U -- CancelarPedido
U -- ConsultarPedido
U -- ModificarPedido
E -- ModificarPedido
E --  AnalisarPedido
B -right-- ConcederContrato
AnalisarPedido .. ConsultarViabilidade : <<include>>

@enduml