@startuml
:Cliente: as U
:Banco: as B
:Empresa: as E

B --|> E

(Criar pedido de locação) as IntroPedido
(Cancelar pedido de locação) as CancelarPedido
(Consultar pedido de locação) as ConsultarPedido
(Alterar pedido de locação) as ModificarPedido

(Avaliar pedido de locação) as AnalisarPedido

(Vincular contrato) as ConsultarViabilidade

(Vincular contrato de crédito) as ConcederContrato

U -- IntroPedido
U -- CancelarPedido
U -- ConsultarPedido
U -- ModificarPedido
E -- ModificarPedido
E --  AnalisarPedido
B -right-- ConcederContrato
AnalisarPedido .. ConsultarViabilidade : <<include>>

@enduml